config/routes.rb
Rails.application.routes.draw do

  resources :images, only: [:index, :new, :create, :show] do
    resources :image_crops, only: [:new, :create]
  end

  resources :pages, only: [:new, :create, :edit]

end

app/models/image.rb
require 'carrierwave/orm/activerecord'

class Image < ActiveRecord::Base
  mount_uploader :file, ImageUploader
  has_many :crops, class_name: "ImageCrop"
end

app/models/image_crop.rb
class ImageCrop < ActiveRecord::Base
  belongs_to :image
  mount_base64_uploader :file, CropUploader
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :header_crop, class_name: 'ImageCrop'
  belongs_to :sidebar_crop, class_name: 'ImageCrop'
  belongs_to :logo, class_name: 'ImageCrop'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/image_crops_controller.rb
class ImageCropsController < ApplicationController
  def new
    @image = Image.find params[:image_id]
    @crop = @image.crops.build
  end

  def create
    @image = Image.find params[:image_id]
    params.require(:image_crop).each do |crop|
      @image.crops.create! crop.permit(:file)
    end
    redirect_to @image
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end

  def create
    @image = Image.create params.require(:image).permit(:file)
    redirect_to image_path(@image)
  end

  def show
    @image = Image.find params[:id]
  end

  def index
    @images = Image.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def new
    @page = Page.new
  end

  def create
    @page = Page.create! params.require(:page).permit(:title)
    redirect_to edit_page_path(@page)
  end

  def edit
    @page = Page.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_crops_helper.rb
module ImageCropsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/image_crops/create.html.erb
<h1>ImageCrops#create</h1>
<p>Find me in app/views/image_crops/create.html.erb</p>

app/views/image_crops/new.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'image_crops', media: 'all', 'data-turbolinks-track' => true %>
<% end -%>
<h1>New Crop</h1>

  <div class="work-area">

    <!-- <div class="module ban-t">
      <a href="#">
        <img src="/img/adsense/adsense_185665_adformat-text_728x90_en.png" alt="">
      </a>
    </div> -->

    <div class="module">
      <div class="panel">
        <ul class="tabs">
          <li class="active">
            <a href="#1"><b>1</b></a><span class="ext-title">Original size --- x ---</span>
          </li>
          <li class="close-panel">
            <a href="#"><span class="arrow-up">&#9650;</span><span class="arrow-down">&#9660;</span></a>
          </li>
        </ul>
        <div class="content p0">
          <div class="cnt">
            <div class="crop-container">
              <%= image_tag @image.file.url, id: 'src' %>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>


  <div class="right-column">

    <!-- <div class="module add-this">
      <div class="addthis_toolbox addthis_default_style ">
        <a class="addthis_button_preferred_1"></a>
        <a class="addthis_button_preferred_2"></a>
        <a class="addthis_button_preferred_3"></a>
        <a class="addthis_button_preferred_4"></a>
        <a class="addthis_button_compact"></a>
        <a class="addthis_counter addthis_bubble_style"></a>
      </div>
      <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-529249843fff5cc2"></script>
    </div> -->

    <div class="module">
      <div class="panel">
        <ul class="tabs">
          <li class="active">
            <a href="#1">Resulting images</a>
          </li>
          <li>
            <a href="#2">Help</a>
          </li>
          <li>
            <a href="#3">Log</a>
          </li>
          <li class="close-panel">
            <a href="#"><span class="arrow-up">&#9650;</span><span class="arrow-down">&#9660;</span></a>
          </li>
        </ul>
        <div class="content">
          <div class="cnt p0">
            <div class="cnt">
              <input type="button" value="Save all as ZIP" title="Save all as ZIP" class="btn">
              <input id="delete-all-crops" type="button" value="Delete all" title="Delete all crops" class="btn">
            </div>
            <hr>

            <input id="master-crop" class="btn mr4 big red" type="button" value="Crop all areas in image">
            <br/>
            <p class="intro">Resulting images will be displayed here...</p>
            <div class="resulting-crops">
              <%= form_for [@image, @crop], id: 'crops-values' do |f| %>
                <%= f.submit "Upload crops" %>
              <% end -%>
            </div>
          </div>
          <div class="cnt">
            Help videos
          </div>
          <div class="cnt">
            <textarea name="log" id="log"></textarea>
          </div>
        </div>
      </div>
    </div>


  </div>

app/views/images/index.html.erb
<h1>Imágenes</h1>

<ul>
  <% @images.each do |image| %>
    <li><%= link_to image_tag( image.file, width: "240px"), image %></li>
  <% end -%>
</ul>

app/views/images/new.html.erb
<h1>Upload image</h1>

<%= form_for @image do |f| %>

  <%= f.file_field :file %>

  <%= f.submit %>

<% end %>

app/views/images/show.html.erb
<h1>Image <%= @image.id %> </h1>

<%= image_tag @image.file.url %>

<h2>Recortes</h2>

<p>
  <%= link_to 'Nuevo recorte', new_image_image_crop_path(@image) %>
</p>

<% @image.crops.each do |crop| %>
  <%= image_tag crop.file %>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoImageCrop</title>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>

<%= yield %>


</body>
</html>

app/views/pages/edit.html.erb
<h1>Edit <%= @page.title %></h1>

<h2>Logo</h2>

<%= image_tag @page.logo %>
<%= link_to "New crop", edit_page_page_crop_path(@page, :logo)%>

<h2>Header</h2>

<%= image_tag @page.header_crop %>
<%= link_to "New crop", edit_page_page_crop_path(@page, :header_crop)%>

<h2>Sidebar</h2>

<%= image_tag @page.sidebar_crop %>
<%= link_to "New crop", edit_page_page_crop_path(@page, :sidebar_crop)%>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= form_for @page do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end -%>